### ISSUE TITLE
{"error":"Valve's servers appear to be offline, please try again later","code":5}

### ISSUE THREAD

**Issue by aboyobam** [Step7750/CSGOFloat#10]
Doesnt matter what I do, I always get this error. 

Updating Game Files...
Logging in *****bot
*****bot Generating TOTP Code from shared_secret
*****bot About to connect
Listening for HTTP on port: 1739
Connected to the database
*****bot Connected
Fetched items_game_cdn.txt
Fetched csgo_english.txt
*****bot Log on OK
*****bot Received servers.
Fetched items_game.txt

Please help

**Comment by Muritavo** [comment]
Hi friend, are you sure the account you are using has CSGO?

**Comment by Step7750** [comment]
As @Muritavo said, you need to own CSGO on the account as stated in the readme.
