### ISSUE TITLE
Add Names of Rarity and Quality Attributes

### ISSUE THREAD

**Issue by Step7750** [Step7750/CSGOFloat#17]
It is useful to know the name of the rarity and quality attributes such as whether the weapon is Souvenir or Prototype along with the rarity of Classified, Covert, Contraband etc...

Currently the API returns the rarity and quality index within the items_game file, but we can parse it and return the English attribute names.

**Comment by tutyamxx** [comment]
How exactly do i translate the quality of the skin? Example: (Well-Worn), (Battle-Scarred)? quality param returns 4 always. Could you provide me a quick example?

**Comment by Step7750** [comment]
@tutyamxx Your implementation has a couple issues (gap between 0.38, 0.39 and 0.45, 0.46) and you should compare with floats rather than strings. Quality indicates Souvenir, Stattrak, etc.. not the wear.

v3.0 will have a `wear_name` property in the response along with the full item name.

**Comment by tutyamxx** [comment]
Oh well i will wait for the next update too. Thanks for replying. Any eta?

**Comment by Step7750** [comment]
@tutyamxx There's a PR open right now #29, no eta. I'll need to do some cache configuration changes once it does get merged.

**Comment by Step7750** [comment]
@tutyamxx v3.0 is now deployed, let me know if you have issues.

**Comment by tutyamxx** [comment]
Will test this asap when i arrive at home

**Comment by tutyamxx** [comment]
itemid_int returns 0 in all the cases?

**Comment by Step7750** [comment]
Thanks for catching itemid_int, it's deprecated and has now been removed in favour of `itemid`. This will be shortly deployed and instantly visible on non-cached responses.

`customname` hasn't been returned from Steam in years, you can see that the name tag isn't visible in the preview window when inspecting an item in game as well.
