### ISSUE TITLE
Help with ExpressJS

### ISSUE THREAD

**Issue by tabam1** [Step7750/CSGOFloat#30]
Can you help me with "queue" in expressJS ?

**Comment by Step7750** [comment]
Please elaborate your issue since this seems off-topic

**Comment by Step7750** [comment]
Our response time is typically 500ms for uncached requests, so I don't know what API endpoint you're using.

This is off-topic but you'd want to use async HTTP calls. ExpressJS isn't relevant to this since you seem to be talking about clients consuming the API.

**Comment by tabam1** [comment]
In your npm csgofloat I can send eg 10 requests and for about 0.5s I have 10 results.

**Comment by tabam1** [comment]
app.get('/', function(req, res) {
    console.log('Start');
	setTimeout(function(){
		res.status(200).json({
		    "msg": "test",
		});
	}, 500);
});

10x Request i have last results in 5s. I want 10 request and last results in 0.5s

**Comment by Step7750** [comment]
Are you running a client or server? Are you consuming the public API?

If you are running a client, you need to send asynchronous HTTP GET calls to the server in order to not wait for each one to finish before the next.

If you are running a server, you need to set the max simultaneous requests per IP amount.

**Comment by tabam1** [comment]
Maybe you'll understand that: https://pastebin.com/wDgfVFdN

**Comment by Step7750** [comment]
I just simulated your example in the latest Chrome release and your calls should be async. Your issue doesn't seem to relate to the server-side code of this repo.

**Comment by tabam1** [comment]
"If you are running a server, you need to set the max simultaneous requests per IP amount." I think is this, how set the max ?

**Comment by Step7750** [comment]
https://github.com/Step7750/CSGOFloat/blob/master/config.example.js#L62

**Comment by tabam1** [comment]
You test my code from pastebin yes ? and get this: 
g(); // results in ~ 500ms.
g(); // results in ~ 1000ms.
g(); // results in ~ 1500ms.

or 

g(); // results in ~ 500ms.
g(); // results in ~ 500ms.
g(); // results in ~ 500ms.


????

**Comment by tabam1** [comment]
The point is that before he executes the second request he must complete the first. I want it to be x request at once

**Comment by Step7750** [comment]
As I've already stated I got the following:

```
g(); // results in ~ 500ms.
g(); // results in ~ 500ms.
g(); // results in ~ 500ms.
```

**Comment by tabam1** [comment]
I get 500/1000/1500 if i set timeout 500 on every request ...

**Comment by Step7750** [comment]
Are you running the code in this repo?

**Comment by tabam1** [comment]
What ? "in this repo" ?

**Comment by tabam1** [comment]
This nodeJs code: https://pastebin.com/hwHQek2A And if i request Ajax 5x. i get 
[22:38:17:177] Start
[22:38:17:772] Start
[22:38:18:376] Start
[22:38:18:952] Start
[22:38:19:514] Start

**Comment by Step7750** [comment]
This depends on your browser, or whatever client you're using to perform requests with.

**Comment by tabam1** [comment]
I sent you via ajax on your api and made several requests at the same time ehhhh

**Comment by Step7750** [comment]
Do you have more than one bot on your server? As I said before, each bot can only request once per second to Valve.

**Comment by tabam1** [comment]
I have 1821 bots

**Comment by tabam1** [comment]
I test with npm request on nodejs and working ... my browser shit

**Comment by tabam1** [comment]
Thanks for help !!
