### ISSUE TITLE
Some Items Have an Undefined Item Name

### ISSUE THREAD

**Issue by tabam1** [Step7750/CSGOFloat#33]
Try inspect this :) steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20M2084510415594025871A15682606578D14295004447383904395 - undefined | undefined (Field-Tested) I know why

**Comment by Step7750** [comment]
`PaintKit_sp_spray_army_Tag` references `Paintkit_sp_spray_army_Tag` while we do a case sensitive check.

**Comment by Step7750** [comment]
Deployed to our main API server, cached responses will still return the same undefined item names; it'll take some time for those cached responses to expire.
