### ISSUE TITLE
Knives now return "Undefined" in full_item_name in place of "★"

### ISSUE THREAD

**Issue by Art-em1s** [Step7750/CSGOFloat#35]
Examples:
[[1](https://api.csgofloat.com/?url=steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20S76561198434421627A15535176195D14566484420251188166)] | [[2](https://api.csgofloat.com/?url=steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20S76561198337726434A15655437504D9691832474916052707)] | [[3](https://api.csgofloat.com/?url=steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20S76561198106192114A15668569912D12594895033742890786)]

Example of it not effecting normal items:
[[1](https://api.csgofloat.com/?url=steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20S76561198391563738A15507601030D10001586603744473044)] | [[2](https://api.csgofloat.com/?url=steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20S76561198106192114A13627921906D146911639445754803)] | [[3](https://api.csgofloat.com/?url=steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20S76561198106192114A15667326878D14423005159689033349)]

**Comment by Step7750** [comment]
Caused by #34

**Comment by Step7750** [comment]
Pushed into v3.0.2, you can update your instance now. Added an issue for tests in #37.

Our main API instance has been updated and the cache purged since this is a major regression. As a result, all your links return correct info now. Sorry for the inconvenience, this should have been caught in testing.
