### ISSUE TITLE
Error: Valve's servers didn't reply in time

### ISSUE THREAD

**Issue by sap2me** [Step7750/CSGOFloat#53]
Hi, i have this error:
`{'code': 4, 'error': "Valve's servers didn't reply in time"}`
How i can fix this? Thanks. 
`info: Updating Game Files...
info: Logging in lightoox13smurf
debug: lightoox13smurf Generating TOTP Code from shared_secret
debug: lightoox13smurf About to connect
info: Listening for HTTP on port: 80
error: Failed to fetch schema.json
debug: Fetched items_game_cdn.txt
info: lightoox13smurf Log on OK
debug: Fetched csgo_english.txt
debug: Fetched items_game.txt
info: lightoox13smurf Initiating GC Connection
info: lightoox13smurf CSGO Client Ready!
debug: lightoox13smurf Fetching for 16510096052
debug: Received itemData for 16510096052
warn: Request Timeout for 16510096052
warn: Job Failed! S: 0 A: 16510096052 D: 14034956153617423917 M: 3246458172236441944 IP: ::ffff:127.0.0.1`

**Comment by Step7750** [comment]
Please provide the inspect link and how you're calling the API

**Comment by sap2me** [comment]
http://127.0.0.1/?url=steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20S76561198028885652A16915676460D10295940039559056006

`def get_float(url, session):
	#url = "https://api.csgofloat.com/?url={}".format(url)
	url = "http://127.0.0.1/?url={}".format(url)
	response = session.get(url)
	data = response.json()
	return data`

It dont work in browser too, but i have no problem using api.csgofloat.com.
Maybe the problem is this error? 
![image](https://user-images.githubusercontent.com/47041160/67695765-4f34d900-f9ae-11e9-99bd-212f486b33a4.png)

**Comment by sap2me** [comment]
I just install csgofloat via npm

**Comment by Step7750** [comment]
Try cloning the master branch on GitHub and see if that fixes your issue.

**Comment by sap2me** [comment]
Thanks, it works.

**Comment by usmanrehmani** [comment]
how to use this in laravel 9?
