### ISSUE TITLE
Missing sticker name

### ISSUE THREAD

**Issue by Art-em1s** [Step7750/CSGOFloat#55]
`{
"stickerId": 242,
"slot": 2,
"codename": "dhw2014_dignitas_gold",
"material": "dhw2014/dignitas_gold"
},`

Is missing a name, replicateable [here](https://api.csgofloat.com/?url=steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20S76561198191076522A9762701305D4929766126514208402)

**Comment by Step7750** [comment]
It seems like Valve has a different tag for the sticker name than in the items_game.txt file.
`csgo_english.txt` -> `StickerKit_dhw2014_teamdignitas_gold`
`items_game` -> `StickerKit_dhw2014_dignitas_gold`

Does the game even display the name of this sticker properly?

**Comment by Art-em1s** [comment]
Interestingly, no. As far as steam is concerned ([example](https://w1z0.xyz/i/2kDgJaA5Mv.png)) the sticker doesn't even exist.

**Comment by Step7750** [comment]
Seems a little bit hacky to make a manual map for this one sticker, I may decide to do it in the future but it seems to be low priority.

**Comment by Step7750** [comment]
Closing this issue for now since Steam has similar behaviour for the incorrectly mapped sticker.
