### ISSUE TITLE
Invalid Inspect Link Structure

### ISSUE THREAD

**Issue by crazychris2404** [Step7750/CSGOFloat#56]
i have used the following code to use your api 
```
<?php
if(isset($_GET['url']) and ($_GET['url']) != '') {
    $inspecturl = $_GET['url'];
    $url2 = 'https://api.csgofloat.com/?url='.$inspecturl; 
    #echo $url;
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_URL, $url2);
    $result = curl_exec($ch);
    curl_close($ch);

    $obj = json_decode($result);
    if (isset($obj->iteminfo)){
       echo $obj->iteminfo->weapon_type . ' - '. $obj->iteminfo->item_name ;
       echo "<br>";
       echo $obj->iteminfo->floatvalue;
    }else{
       echo $result;
    }
} else
echo 'please enter inspect url';
?>
```
and it gives the response of Invalid Inspect Link Structure 
when i tested the url to check if everything correct that url gave me the valid data however my code didnt

**Comment by crazychris2404** [comment]
the attempt was myurl?url=steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20S76561198345398814A17272724866D921133459672994387

**Comment by Perplex** [comment]
Can you print out url2?

**Comment by crazychris2404** [comment]
https://api.csgofloat.com/?url=steam://rungame/730/76561202255233023/ csgo_econ_action_preview S76561198345398814A17272724866D921133459672994387

**Comment by crazychris2404** [comment]
i have fixed the issue it was the fact the URL was sending with a space not %20 so upon replacing the space it now works as intended please consider adding that to docs

**Comment by Step7750** [comment]
Yeah, you need to URL encode the URL. Many (most?) http client libraries do
that to escape various elements.
